export enum ChangePeriodsEnum {
  EVERY_HOUR = 'EVERY_HOUR',
  EVERY_3_HOURS = 'EVERY_3_HOURS',
  EVERY_DAY = 'EVERY_DAY',
  EVERY_3_DAY = 'EVERY_3_DAY',
  EVERY_WEEK = 'EVERY_WEEK',
  EVERY_2_WEEK = 'EVERY_2_WEEK',
  EVERY_MONTH = 'EVERY_MONTH',

  //for debugging
  EVERY_15_SECONDS = 'EVERY_15_SECONDS',
  EVERY_MINUTE = 'EVERY_MINUTE',
}